-- UP MIGRATION
CREATE TABLE samples (
    id SERIAL PRIMARY KEY,
    taxon_id INTEGER NOT NULL REFERENCES taxons(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    derived_from INTEGER REFERENCES samples(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);