//! This file is generated automatically and should not be modified.
//!
//! Any edits you may apply to this document will be overwritten next time the
//! backend is generated. Refrain from making any changes to this file.

//! If you need to make changes to the backend, please modify the `generate_models`
//! document in the `migrations` folder.

mod colors;
pub use colors::*;
mod countries;
pub use countries::*;
mod derived_samples;
pub use derived_samples::*;
mod document_formats;
pub use document_formats::*;
mod font_awesome_icons;
pub use font_awesome_icons::*;
mod login_providers;
pub use login_providers::*;
mod materials;
pub use materials::*;
mod nameplate_categories;
pub use nameplate_categories::*;
mod nameplates;
pub use nameplates::*;
mod notifications;
pub use notifications::*;
mod observation_subjects;
pub use observation_subjects::*;
mod observations;
pub use observations::*;
mod organism_taxa;
pub use organism_taxa::*;
mod organisms;
pub use organisms::*;
mod organizations;
pub use organizations::*;
mod permanence_categories;
pub use permanence_categories::*;
mod project_states;
pub use project_states::*;
mod projects;
pub use projects::*;
mod projects_teams_role_invitations;
pub use projects_teams_role_invitations::*;
mod projects_teams_role_requests;
pub use projects_teams_role_requests::*;
mod projects_teams_roles;
pub use projects_teams_roles::*;
mod projects_users_role_invitations;
pub use projects_users_role_invitations::*;
mod projects_users_role_requests;
pub use projects_users_role_requests::*;
mod projects_users_roles;
pub use projects_users_roles::*;
mod ranks;
pub use ranks::*;
mod roles;
pub use roles::*;
mod sample_container_categories;
pub use sample_container_categories::*;
mod sample_containers;
pub use sample_containers::*;
mod sample_states;
pub use sample_states::*;
mod sample_taxa;
pub use sample_taxa::*;
mod samples;
pub use samples::*;
mod spectra;
pub use spectra::*;
mod spectra_collections;
pub use spectra_collections::*;
mod taxa;
pub use taxa::*;
mod team_states;
pub use team_states::*;
mod teams;
pub use teams::*;
mod teams_teams_role_invitations;
pub use teams_teams_role_invitations::*;
mod teams_users_role_invitations;
pub use teams_users_role_invitations::*;
mod teams_users_role_requests;
pub use teams_users_role_requests::*;
mod teams_users_roles;
pub use teams_users_roles::*;
mod units;
pub use units::*;
mod user_emails;
pub use user_emails::*;
mod users;
pub use users::*;
mod users_users_role_invitations;
pub use users_users_role_invitations::*;
mod users_users_role_requests;
pub use users_users_role_requests::*;
mod users_users_roles;
pub use users_users_roles::*;
