[package]
name = "molecular_formula"
version = "0.1.0"
edition = "2024"

[dependencies]
elements.workspace = true
fmtastic.workspace = true

[dev-dependencies]
strum.workspace = true
criterion.workspace = true

[[bench]]
name = "bench_oxidation_states"
harness = false

[lints]
workspace = true
