[package]
name = "molecular_formula"
version = "0.1.0"
edition = "2024"

[dependencies]
elements.workspace = true
sophia_sparql_client.workspace = true
sophia_api.workspace = true

[lints]
workspace = true
