-- Drop the `spectra_collections_users_roles_updated_at_trigger` trigger on the spectra_collections_users_roles table.

DROP TRIGGER spectra_collections_users_roles_updated_at_trigger ON spectra_collections_users_roles;
DROP FUNCTION spectra_collections_users_roles_updated_at_trigger;
