-- UP MIGRATION
CREATE TABLE IF NOT EXISTS samples (
    id UUID PRIMARY KEY,
    container_id INTEGER NOT NULL UNIQUE REFERENCES sample_containers(id) ON DELETE CASCADE,
    notes TEXT,
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    sampled_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state INTEGER NOT NULL REFERENCES sample_states(id) ON
    DELETE CASCADE
);