/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/tool_categories/src/lib.rs:17
-- tool_categories::ToolCategory
CREATE TYPE ToolCategory AS ENUM (
	'Camera',
	'InsectTrap',
	'CuttingTool',
	'Wrapper',
	'PreciseManipulationTool',
	'BreakingBeads',
	'Gloves',
	'HandCleaningAgent',
	'PaperTowels',
	'VolumeMeasuringTool'
);
/* </end connected objects> */

