//! This module contains the table names enumeration.
//!
//! This module is automatically generated. Do not write anything here.

use serde::Deserialize;
use serde::Serialize;
#[derive(Deserialize, Serialize, Clone, Debug, PartialEq, Eq, Copy)]
pub enum Table {
    Units,
    Procedures,
    ItemCategoryRelationships,
    Kingdoms,
    SampleTaxa,
    ItemContinuousQuantities,
    ItemCategoryUnits,
    DocumentFormats,
    DiscreteUnits,
    ItemUnits,
    ProcedureDiscreteRequirements,
    Phylums,
    ContainerHorizontalRules,
    Projects,
    OrganismDomains,
    ProcedureContinuousRequirements,
    ItemCategories,
    ProjectStates,
    Teams,
    Locations,
    ProjectRequirements,
    UserEmails,
    ItemDiscreteQuantities,
    Items,
    Notifications,
    Documents,
    LoginProviders,
    Roles,
    SpectraCollection,
    ClassRanks,
    Organizations,
    Spectra,
    Users,
    Taxa,
    DerivedSamples,
    ManufacturedItemCategories,
    ContinuousUnits,
    PrimaryUserEmails,
    PublicUsers,
    SampledIndividualTaxa,
    SampleStates,
    Samples,
    ContainerVerticalRules,
    ItemLocations,
    SampledIndividuals,
    SamplingProcedures,
}

impl AsRef<str> for Table {
    fn as_ref(&self) -> &str {
        match self {
            Table::Units => "units",
            Table::Procedures => "procedures",
            Table::ItemCategoryRelationships => "item_category_relationships",
            Table::Kingdoms => "kingdoms",
            Table::SampleTaxa => "sample_taxa",
            Table::ItemContinuousQuantities => "item_continuous_quantities",
            Table::ItemCategoryUnits => "item_category_units",
            Table::DocumentFormats => "document_formats",
            Table::DiscreteUnits => "discrete_units",
            Table::ItemUnits => "item_units",
            Table::ProcedureDiscreteRequirements => "procedure_discrete_requirements",
            Table::Phylums => "phylums",
            Table::ContainerHorizontalRules => "container_horizontal_rules",
            Table::Projects => "projects",
            Table::OrganismDomains => "organism_domains",
            Table::ProcedureContinuousRequirements => "procedure_continuous_requirements",
            Table::ItemCategories => "item_categories",
            Table::ProjectStates => "project_states",
            Table::Teams => "teams",
            Table::Locations => "locations",
            Table::ProjectRequirements => "project_requirements",
            Table::UserEmails => "user_emails",
            Table::ItemDiscreteQuantities => "item_discrete_quantities",
            Table::Items => "items",
            Table::Notifications => "notifications",
            Table::Documents => "documents",
            Table::LoginProviders => "login_providers",
            Table::Roles => "roles",
            Table::SpectraCollection => "spectra_collection",
            Table::ClassRanks => "class_ranks",
            Table::Organizations => "organizations",
            Table::Spectra => "spectra",
            Table::Users => "users",
            Table::Taxa => "taxa",
            Table::DerivedSamples => "derived_samples",
            Table::ManufacturedItemCategories => "manufactured_item_categories",
            Table::ContinuousUnits => "continuous_units",
            Table::PrimaryUserEmails => "primary_user_emails",
            Table::PublicUsers => "public_users",
            Table::SampledIndividualTaxa => "sampled_individual_taxa",
            Table::SampleStates => "sample_states",
            Table::Samples => "samples",
            Table::ContainerVerticalRules => "container_vertical_rules",
            Table::ItemLocations => "item_locations",
            Table::SampledIndividuals => "sampled_individuals",
            Table::SamplingProcedures => "sampling_procedures",
        }
    }
}
impl std::fmt::Display for Table {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_ref())
    }
}
