-- UP MIGRATION
CREATE TABLE IF NOT EXISTS sample_extract_aliquotes (
    id UUID PRIMARY KEY,
    sample_extract_id INTEGER NOT NULL REFERENCES sample_extracts(id),
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_by INTEGER NOT NULL REFERENCES users(id),
    sampled_by INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NOT NULL REFERENCES users(id),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state_id SMALLINT NOT NULL DEFAULT 1 REFERENCES sample_states(id)
);
