/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:7
-- pgrx_validation::str::must_be_email
CREATE  FUNCTION "must_be_email"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_be_email_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/font_awesome_icons.rs:1437
-- pgrx_validation::font_awesome_icons::must_be_font_awesome_class
CREATE  FUNCTION "must_be_font_awesome_class"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_be_font_awesome_class_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:104
-- pgrx_validation::str::must_be_paragraph
CREATE  FUNCTION "must_be_paragraph"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_be_paragraph_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:23
-- pgrx_validation::str::must_not_be_empty
CREATE  FUNCTION "must_not_be_empty"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_not_be_empty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:42
-- pgrx_validation::str::must_not_be_padded
CREATE  FUNCTION "must_not_be_padded"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_not_be_padded_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:61
-- pgrx_validation::str::must_not_contain_consecutive_whitespace
CREATE  FUNCTION "must_not_contain_consecutive_whitespace"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_not_contain_consecutive_whitespace_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- web/web_common/pgrx_validation/src/str.rs:83
-- pgrx_validation::str::must_not_contain_control_characters
CREATE  FUNCTION "must_not_contain_control_characters"(
	"value" TEXT /* &str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'must_not_contain_control_characters_wrapper';
/* </end connected objects> */

