CREATE TABLE IF NOT EXISTS login_providers (
  id SMALLSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  icon FAIcon NOT NULL,
  client_id VARCHAR(255) NOT NULL,
  redirect_uri VARCHAR(255) NOT NULL,
  oauth_url VARCHAR(255) NOT NULL,
  scope VARCHAR(255) NOT NULL
);
