"""Submodule to write the SQL operator bindings for the Diesel ORM as loaded from the database."""
from typing import List
import os
from tqdm.auto import tqdm
from constraint_checkers.find_foreign_keys import TableMetadata, SQLOperator

def write_diesel_sql_operator_bindings(table_metadata: TableMetadata):
    """Write the SQL operator bindings for the Diesel ORM as loaded from the database."""
    sql_operators: List[SQLOperator] = table_metadata.get_all_postgres_operators()
    
    with open('src/sql_operator_bindings.rs', 'w', encoding="utf8") as module_document:
        # First thing, we write that this file is automatically generated
        # and discourage the user from editing it manually.

        warning = (
            "//! This file is automatically generated by the code generation suite.\n"
            "//! Do not edit it manually.\n"
            "//!\n"
            "//! This file contains the bindings for the SQL operators in the database.\n\n"
        )

        os.makedirs("src/sql_operator_bindings", exist_ok=True)

        module_document.write(warning)

        for i, sql_operator in tqdm(
            enumerate(sql_operators),
            desc="Writing SQL operator bindings",
            unit="operator",
            total=len(sql_operators),
            leave=False,
        ):
            module_document.write(
                f"mod {sql_operator.sanitize_name()};\n"
                f"pub use {sql_operator.sanitize_name()}::*;\n"
            )

            with open(f"src/sql_operator_bindings/{sql_operator.sanitize_name()}.rs", "w", encoding="utf8") as f:
                f.write(warning)

                try:
                    sql_operator.write_diesel_binding_to_file(f)
                except NotImplementedError as e:
                    raise NotImplementedError(
                        f"Failed to write binding for SQL operator {sql_operator.name}. "
                        f"We are at the {i}th operator out of {len(sql_operators)}."
                    ) from e

    print(f"Successfully wrote {len(sql_operators)} SQL operator bindings to src/sql_operator_bindings.rs.")