-- SQL query creating a mockup of the users table.
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (username),
    UNIQUE (email),
    UNIQUE (username, email)
);

CREATE TABLE projects (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    parent_project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,
    created_by INTEGER NOT NULL REFERENCES users(id),
    updated_by INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    created_by INTEGER NOT NULL REFERENCES users(id),
    updated_by INTEGER NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_members (
    member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    PRIMARY KEY (member_id, team_id)
);

CREATE TABLE IF NOT EXISTS team_projects (
    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, team_id)
);

CREATE TABLE IF NOT EXISTS trackables (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS containers (
    id INTEGER PRIMARY KEY REFERENCES trackables(id) ON DELETE CASCADE,
    parent_container_id INTEGER REFERENCES containers(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS instruments (
    id INTEGER PRIMARY KEY REFERENCES trackables(id) ON DELETE CASCADE,
    brand TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS android_devices (
    id INTEGER PRIMARY KEY REFERENCES instruments(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS freezers (
    id INTEGER PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES containers(id) ON DELETE CASCADE,
    FOREIGN KEY (id) REFERENCES instruments(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS android_freezers (
    id INTEGER PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES freezers(id) ON DELETE CASCADE,
    FOREIGN KEY (id) REFERENCES android_devices(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS gps (
    id INTEGER PRIMARY KEY REFERENCES instruments(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS cameras (
    id INTEGER PRIMARY KEY REFERENCES instruments(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS video_cameras (
    id INTEGER PRIMARY KEY REFERENCES cameras(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS phones (
    id INTEGER PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES gps(id) ON DELETE CASCADE,
    FOREIGN KEY (id) REFERENCES video_cameras(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS android_phones (
    id INTEGER PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES android_devices(id) ON DELETE CASCADE,
    FOREIGN KEY (id) REFERENCES phones(id) ON DELETE CASCADE
);