//! This module contains the nested structs for the database tables.
//!
//! This file is automatically generated. Do not write anything here.

use uuid::Uuid;
use serde::Deserialize;
use serde::Serialize;
use chrono::NaiveDateTime;
use diesel::r2d2::ConnectionManager;
use diesel::r2d2::PooledConnection;
use diesel::prelude::*;
use crate::models::*;
