-- UP MIGRATION
CREATE TABLE samples (
    id SERIAL PRIMARY KEY,
    taxon_id INTEGER NOT NULL REFERENCES taxa(id) ON DELETE CASCADE,
    sample_type_id INTEGER NOT NULL REFERENCES sample_types(id) ON DELETE CASCADE,
    derived_from INTEGER REFERENCES samples(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);