-- SQL to create the projects table.
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (must_not_be_empty(name)),
    description TEXT NOT NULL CHECK (must_not_be_empty(description)),
    state_id SMALLINT NOT NULL DEFAULT 1,
    icon TEXT NOT NULL CHECK (must_be_font_awesome_class(icon)),
    color_id SMALLINT NOT NULL DEFAULT 1,
    parent_project_id INTEGER,
    budget FLOAT,
    expenses FLOAT,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expected_end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (state_id) REFERENCES project_states(id),
    FOREIGN KEY (color_id) REFERENCES colors(id),
    FOREIGN KEY (parent_project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (must_be_distinct_i32(parent_project_id, id)),
    CHECK (must_be_distinct(name, description))
);
