[package]
name = "core-structures-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
time-requirements.workspace = true
quote.workspace = true
const_format.workspace = true
webcodegen.workspace = true
reference-docker.workspace = true
init-db.workspace = true
diesel-async = { workspace = true, features = ["postgres"] }

[lints]
workspace = true
