[package]
name = "core-structures-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
taxonomy-fetcher.workspace = true
csqlv.workspace = true
tokio.workspace = true
font_awesome.workspace = true
webcodegen.workspace = true
diesel_migrations_utils.workspace = true
time-requirements.workspace = true
quote.workspace = true
const_format.workspace = true
diesel = { workspace = true, features = ["postgres"] }
