pub mod basic_input;
pub use basic_input::*;
pub mod input_error;
pub use input_error::*;
pub mod file_input;
pub use file_input::*;
pub mod gps_input;
pub use gps_input::*;
pub mod map_input;
pub use map_input::*;
pub mod datalist;
pub use datalist::*;
pub mod checkbox;
pub use checkbox::*;
pub mod barcode_scanner;
pub use barcode_scanner::*;
mod file_like;
