-- UP MIGRATION
CREATE TABLE samples (
    id SERIAL PRIMARY KEY,
    derived_from INTEGER REFERENCES samples(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);