//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Bpcharlike, " ~~ ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `~~` operator.
pub trait HasBpcharlike:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::CChar>
{
    /// The function to create the `Bpcharlike` struct representing the `~~` operator.
    fn bpcharlike<Rhs>(self, rhs: Rhs) -> Bpcharlike<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Text>,
    {
        Bpcharlike::new(self, rhs.as_expression())
    }
}

impl<T> HasBpcharlike for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::CChar>
{
}
