//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DateMi, " - ", diesel::sql_types::Integer, backend: diesel::pg::Pg);
/// Trait for the `-` operator.
pub trait HasDateMi:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
    /// The function to create the `DateMi` struct representing the `-` operator.
    fn date_mi<Rhs>(self, rhs: Rhs) -> DateMi<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Date>,
    {
        DateMi::new(self, rhs.as_expression())
    }
}

impl<T> HasDateMi for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
}
