//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DistPl, " <-> ", diesel::sql_types::Double, backend: diesel::pg::Pg);
/// Trait for the `<->` operator.
pub trait HasDistPl:
    Sized + diesel::expression::Expression<SqlType = crate::database::sql_type_bindings::Point>
{
    /// The function to create the `DistPl` struct representing the `<->` operator.
    fn dist_pl<Rhs>(self, rhs: Rhs) -> DistPl<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        DistPl::new(self, rhs.as_expression())
    }
}

impl<T> HasDistPl for T where
    T: Sized + diesel::expression::Expression<SqlType = crate::database::sql_type_bindings::Point>
{
}
