//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Float4div, " / ", diesel::sql_types::Float, backend: diesel::pg::Pg);
/// Trait for the `/` operator.
pub trait HasFloat4div:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Float>
{
    /// The function to create the `Float4div` struct representing the `/` operator.
    fn float4div<Rhs>(self, rhs: Rhs) -> Float4div<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Float>,
    {
        Float4div::new(self, rhs.as_expression())
    }
}

impl<T> HasFloat4div for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Float>
{
}
