//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(GeometryContained3d, " <<@ ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<<@` operator.
pub trait HasGeometryContained3d:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `GeometryContained3d` struct representing the `<<@` operator.
    fn geometry_contained_3d<Rhs>(self, rhs: Rhs) -> GeometryContained3d<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        GeometryContained3d::new(self, rhs.as_expression())
    }
}

impl<T> HasGeometryContained3d for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
