//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Int2div, " / ", diesel::sql_types::SmallInt, backend: diesel::pg::Pg);
/// Trait for the `/` operator.
pub trait HasInt2div:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::SmallInt>
{
    /// The function to create the `Int2div` struct representing the `/` operator.
    fn int2div<Rhs>(self, rhs: Rhs) -> Int2div<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::SmallInt>,
    {
        Int2div::new(self, rhs.as_expression())
    }
}

impl<T> HasInt2div for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::SmallInt>
{
}
