//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Int28mul, " * ", diesel::sql_types::BigInt, backend: diesel::pg::Pg);
/// Trait for the `*` operator.
pub trait HasInt28mul:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::SmallInt>
{
    /// The function to create the `Int28mul` struct representing the `*` operator.
    fn int28mul<Rhs>(self, rhs: Rhs) -> Int28mul<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::BigInt>,
    {
        Int28mul::new(self, rhs.as_expression())
    }
}

impl<T> HasInt28mul for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::SmallInt>
{
}
