//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Int8shr, " >> ", diesel::sql_types::BigInt, backend: diesel::pg::Pg);
/// Trait for the `>>` operator.
pub trait HasInt8shr:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::BigInt>
{
    /// The function to create the `Int8shr` struct representing the `>>` operator.
    fn int8shr<Rhs>(self, rhs: Rhs) -> Int8shr<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Integer>,
    {
        Int8shr::new(self, rhs.as_expression())
    }
}

impl<T> HasInt8shr for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::BigInt>
{
}
