//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(IntegerPlDate, " + ", diesel::sql_types::Date, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasIntegerPlDate:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Integer>
{
    /// The function to create the `IntegerPlDate` struct representing the `+` operator.
    fn integer_pl_date<Rhs>(self, rhs: Rhs) -> IntegerPlDate<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Date>,
    {
        IntegerPlDate::new(self, rhs.as_expression())
    }
}

impl<T> HasIntegerPlDate for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Integer>
{
}
