//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(IntervalPlTimestamptz, " + ", diesel::sql_types::Timestamp, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasIntervalPlTimestamptz:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
    /// The function to create the `IntervalPlTimestamptz` struct representing the `+` operator.
    fn interval_pl_timestamptz<Rhs>(self, rhs: Rhs) -> IntervalPlTimestamptz<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        IntervalPlTimestamptz::new(self, rhs.as_expression())
    }
}

impl<T> HasIntervalPlTimestamptz for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
}
