//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(IntervalDiv, " / ", diesel::sql_types::Interval, backend: diesel::pg::Pg);
/// Trait for the `/` operator.
pub trait HasIntervalDiv:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
    /// The function to create the `IntervalDiv` struct representing the `/` operator.
    fn interval_div<Rhs>(self, rhs: Rhs) -> IntervalDiv<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Double>,
    {
        IntervalDiv::new(self, rhs.as_expression())
    }
}

impl<T> HasIntervalDiv for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
}
