//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(LinePerp, " ?-| ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `?-|` operator.
pub trait HasLinePerp:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `LinePerp` struct representing the `?-|` operator.
    fn line_perp<Rhs>(self, rhs: Rhs) -> LinePerp<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        LinePerp::new(self, rhs.as_expression())
    }
}

impl<T> HasLinePerp for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
