//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(LsegInterpt, " # ", postgis_diesel::sql_types::Geometry, backend: diesel::pg::Pg);
/// Trait for the `#` operator.
pub trait HasLsegInterpt:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `LsegInterpt` struct representing the `#` operator.
    fn lseg_interpt<Rhs>(self, rhs: Rhs) -> LsegInterpt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        LsegInterpt::new(self, rhs.as_expression())
    }
}

impl<T> HasLsegInterpt for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
