//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimestampLeDate, " <= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<=` operator.
pub trait HasTimestampLeDate:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
    /// The function to create the `TimestampLeDate` struct representing the `<=` operator.
    fn timestamp_le_date<Rhs>(self, rhs: Rhs) -> TimestampLeDate<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Date>,
    {
        TimestampLeDate::new(self, rhs.as_expression())
    }
}

impl<T> HasTimestampLeDate for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
}
