//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimestampNeTimestamptz, " <> ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<>` operator.
pub trait HasTimestampNeTimestamptz:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
    /// The function to create the `TimestampNeTimestamptz` struct representing the `<>` operator.
    fn timestamp_ne_timestamptz<Rhs>(
        self,
        rhs: Rhs,
    ) -> TimestampNeTimestamptz<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        TimestampNeTimestamptz::new(self, rhs.as_expression())
    }
}

impl<T> HasTimestampNeTimestamptz for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
}
