//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimePlInterval, " + ", diesel::sql_types::Time, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasTimePlInterval:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
    /// The function to create the `TimePlInterval` struct representing the `+` operator.
    fn time_pl_interval<Rhs>(self, rhs: Rhs) -> TimePlInterval<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Interval>,
    {
        TimePlInterval::new(self, rhs.as_expression())
    }
}

impl<T> HasTimePlInterval for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
}
