//! Test submodule for parsing molecular formulas

use std::str::FromStr;

use molecular_formulas::MolecularFormula;

const COMPLEX_FORMULAS: &[&str] = &[
    "C14H14ClN3OS",
    "C54H70N18O6",
    "K4[Fe(CN)6]",
    "[Co(NH3)5Cl]Cl2",
    "[Cr(H2O)6]3+",
    "[Fe(CN)6]4-",
    "Na3[AlF6]",
    "C55H72O5N4Mg",
    "C149H240N40O38S",
    "[Cu(C2H4(NH2)2)2(H2O)2]SO4.H2O",
    "C76H104N20O24S4Zn",
    "(NH4)6[Mo7O24].4H2O",
    "C6H6.CH3NO2",
    "C6H6.CHCl3",
    "C6H5NO2.HNO3",
];

const NAMED_FORMULAS: &[(&str, &str)] = &[
    ("Acetic acid formula", "CH3COOH"),
    ("Aluminium hydroxide formula", "Al(OH)3"),
    ("Acetate formula", "CH3COO-"),
    ("Acetone formula", "C3H6O"),
    ("Aluminium acetate formula", "C6H9AlO6"),
    ("Aluminium bromide formula", "AlBr3"),
    ("Aluminium carbonate formula", "Al2(CO3)3"),
    ("Aluminium chloride formula", "AlCl3"),
    ("Aluminium fluoride formula", "AlF3"),
    ("Aluminium formula", "Al"),
    ("Aluminium iodide formula", "AlI3"),
    ("Aluminium oxide formula", "Al2O3"),
    ("Aluminium phosphate formula", "AlPO4"),
    ("Amino acid formula", "H2NCHRCOOH"),
    ("Ammonia formula", "NH3"),
    ("Ammonium dichromate formula", "Cr2H8N2O7"),
    ("Ammonium acetate formula", "C2H3O2NH4"),
    ("Ammonium bicarbonate formula", "NH4HCO3"),
    ("Ammonium bromide formula", "NH4Br"),
    ("Ammonium carbonate formula", "(NH4)2CO3"),
    ("Ammonium chloride formula", "NH4Cl"),
    ("Ammonium hydroxide formula", "NH4OH"),
    ("Ammonium iodide formula", "NH4I"),
    ("Ammonium nitrate formula", "NH4NO3"),
    ("Aluminium sulfide formula", "Al2S3"),
    ("Ammonium nitrite formula", "NH4NO2"),
    ("Ammonium oxide formula", "(NH4)2O"),
    ("Ammonium phosphate formula", "(NH4)3PO4"),
    ("Ammonium sulfate formula", "(NH4)2SO4"),
    ("Ammonium sulfide formula", "(NH4)2S"),
    ("Argon gas formula", "Ar"),
    ("Ascorbic acid formula", "C6H8O6"),
    ("Barium acetate formula", "Ba(C2H3O2)2"),
    ("Barium bromide formula", "BaBr2"),
    ("Barium chloride formula", "BaCl2"),
    ("Barium fluoride formula", "BaF2"),
    ("Barium hydroxide formula", "Ba(OH)2"),
    ("Barium iodide formula", "BaI2"),
    ("Barium nitrate formula", "Ba(NO3)2"),
    ("Barium oxide formula", "BaO"),
    ("Barium phosphate formula", "Ba3O8P2"),
    ("Barium sulfate formula", "BaSO4"),
    ("Benzene formula", "C6H6"),
    ("Benzoic acid formula", "C7H6O2"),
    ("Bicarbonate formula", "CHO3-"),
    ("Bleach formula", "NaClO"),
    ("Boric acid formula", "H3BO3"),
    ("Potassium Bromate formula", "KBrO3"),
    ("Bromic acid formula", "HBrO3"),
    ("Bromine formula", "Br"),
    ("Butane formula", "C4H10"),
    ("Butanoic acid formula", "C4H8O2"),
    ("Calcium acetate formula", "C4H6CaO4"),
    ("Calcium bromide formula", "CaBr2"),
    ("Calcium carbonate formula", "CaCO3"),
    ("Calcium hydride formula", "CaH2"),
    ("Calcium hydroxide formula", "Ca(OH)2"),
    ("Calcium iodide formula", "CaI2"),
    ("Calcium nitrate formula", "Ca(NO3)2"),
    ("Calcium oxide formula", "CaO"),
    ("Carbon monoxide formula", "CO"),
    ("Carbon tetrachloride formula", "CCl4"),
    ("Carbonic acid formula", "H2CO3"),
    ("Calcium phosphate formula", "Ca3(PO4)2"),
    ("Carbonic acid formula", "H2CO3"),
    ("Citric acid formula", "C6H8O7"),
    ("Chlorate formula", "ClO-3"),
    ("Chlorine formula", "Cl"),
    ("Chlorine gas formula", "Cl2"),
    ("Chlorous acid formula", "HClO2"),
    ("Chromic acid formula", "H2CrO4"),
    ("Citric acid formula", "C6H8O7"),
    ("Copper ii carbonate formula", "CuCO3"),
    ("Copper ii nitrate formula", "Cu(NO3)2"),
    ("Cyanide formula", "CN-"),
    ("Dichromate formula", "K2Cr2O7"),
    ("Dihydrogen monoxide formula", "H2O"),
    ("Dinitrogen monoxide formula", "N2O"),
    ("Dinitrogen pentoxide formula", "N2O5"),
    ("Dinitrogen trioxide formula", "N2O3"),
    ("Ethanol formula", "C2H5OH"),
    ("Iron oxide formula", "Fe2O3"),
    ("Ethylene glycol formula", "C2H6O2"),
    ("Fluorine gas formula", "F2"),
    ("Aluminium bromide formula", "AlBr3"),
    ("Aluminium sulfide formula", "Al2S3"),
    ("Ammonium carbonate formula", "(NH4)2CO3"),
    ("Ammonium nitrate formula", "(NH4)(NO3)"),
    ("Ammonium phosphate formula", "(NH4)3PO4"),
    ("Barium chloride formula", "BaCl2"),
    ("Barium sulfate formula", "BaSO4"),
    ("Calcium nitrate formula", "Ca(NO3)2"),
    ("Carbon monoxide formula", "CO"),
    ("Carbon tetrachloride formula", "CCl4"),
    ("Carbonic acid formula", "H2CO3"),
    ("Hydrofluoric acid formula", "HF"),
    ("Hydroiodic acid formula", "HI"),
    ("Hypochlorous acid formula", "HClO"),
    ("Lithium phosphate formula", "Li3PO4"),
    ("Magnesium nitrate formula", "MgNO3"),
    ("Magnesium phosphate formula", "Mg3(PO4)2"),
    ("Nitrogen monoxide formula", "NO"),
    ("Nitrous acid formula", "HNO2"),
    ("Potassium carbonate formula", "K2CO3"),
    ("Potassium iodide formula", "KI"),
    ("Potassium nitrate formula", "KNO3"),
    ("Potassium phosphate formula", "KH2PO4"),
    ("Sodium carbonate formula", "Na2CO3"),
    ("Sodium oxide formula", "Na2O"),
    ("Fructose chemical formula", "C6H12O6"),
    ("Glycerol formula", "C3H8O3"),
    ("Helium gas formula", "He"),
    ("Hexane formula", "C6H14"),
    ("Hydrobromic acid formula", "HBr"),
    ("Hydrochloric acid formula", "HCl"),
    ("Hydrocyanic acid formula", "HCN"),
    ("Hydrofluoric acid formula", "HF"),
    ("Hydrogen carbonate formula", "CHO3-"),
    ("Hydrogen gas formula", "H2"),
    ("Hydrogen peroxide formula", "H2O2"),
    ("Hydrogen phosphate formula", "H3PO4"),
    ("Hydrogen sulfate formula", "HSO4-"),
    ("Hydroiodic acid formula", "HI"),
    ("Hydrosulfuric acid formula", "H2SO4"),
    ("Hydroxide ion formula", "OH-"),
    ("Hypobromous acid formula", "HBrO"),
    ("Hypochlorite formula", "NaClO"),
    ("Hypochlorous acid formula", "HClO"),
    ("Hypoiodous acid formula", "HIO"),
    ("Iodic acid formula", "HIO3"),
    ("Iodide ion formula", "I-"),
    ("Iodine formula", "I2"),
    ("Iron (iii) nitrate formula", "Fe(NO3)3"),
    ("Iron (ii) oxide formula", "FeO"),
    ("Iron (iii) carbonate formula", "Fe2(CO3)3"),
    ("Iron (iii) hydroxide formula", "Fe(OH)3"),
    ("Iron (iii) oxide formula", "Fe2O3"),
    ("Iron (iii) chloride formula", "FeCl3"),
    ("Lactic acid formula", "C3H6O3"),
    ("Lead acetate formula", "Pb(C2H3O2)2"),
    ("Lead (ii) acetate formula", "Pb(C2H3O2)2"),
    ("Lead iodide formula", "PbI2"),
    ("Lead (iv) oxide formula", "PbO2"),
    ("Lead nitrate formula", "Pb(NO3)2"),
    ("Lithium bromide formula", "LiBr"),
    ("Lithium chloride formula", "LiCl"),
    ("Lithium hydroxide formula", "LiOH"),
    ("Lithium iodide formula", "LiI"),
    ("Lithium oxide formula", "Li2O"),
    ("Lithium phosphate formula", "Li3PO4"),
    ("Magnesium acetate formula", "Mg(CH3COO)2"),
    ("Magnesium bicarbonate formula", "C2H2MgO6"),
    ("Magnesium carbonate formula", "MgCO3"),
    ("Magnesium chloride formula", "MgCl2"),
    ("Magnesium hydroxide formula", "Mg(OH)2"),
    ("Magnesium iodide formula", "MgI2"),
    ("Magnesium nitrate formula", "Mg(NO3)2"),
    ("Magnesium nitride formula", "Mg3N2"),
    ("Magnesium carbonate formula", "MgCO3"),
    ("Magnesium bromide formula", "MgBr2"),
    ("Magnesium oxide formula", "MgO"),
    ("Magnesium phosphate formula", "Mg3(PO4)2"),
    ("Magnesium sulfate formula", "MgSO4"),
    ("Magnesium sulfide formula", "MgS"),
    ("Methane formula", "CH4"),
    ("Methanol formula", "CH3OH"),
    ("Nickel acetate formula", "Ni(C2H3O2)2"),
    ("Nickel nitrate formula", "Ni(NO3)2"),
    ("Nitric acid formula", "HNO3"),
    ("Nitride formula", "N3-"),
    ("Nitrite formula", "NO2-"),
    ("Nitrogen dioxide formula", "NO2"),
    ("Nitrogen monoxide formula", "NO"),
    ("Nitrous acid formula", "HNO2"),
    ("Oxalic acid formula", "H2C2O4"),
    ("Oxygen formula", "O2"),
    ("Ozone formula", "O3"),
    ("Perbromic acid formula", "HBrO4"),
    ("Potassium Permanganate formula", "KMnO4"),
    ("Permanganate ion formula", "MnO4-"),
    ("Sodium hydrogen phosphate formula", "Na2HPO4"),
    ("Sodium formate formula", "HCOONa"),
    ("Phosphoric acid formula", "H3PO4"),
    ("Phosphorus pentachloride formula", "PCl5"),
    ("Phosphorus trichloride formula", "PCl3"),
    ("Potassium acetate formula", "CH3CO2K"),
    ("Potassium bicarbonate formula", "KHCO3"),
    ("Potassium carbonate formula", "K2CO3"),
    ("Potassium chlorate formula", "KClO3"),
    ("Potassium hydrogen phosphate formula", "K2HPO4"),
    ("Potassium chloride formula", "KCl"),
    ("Potassium chromate formula", "CrK2O4"),
    ("Potassium cyanide formula", "KCN"),
    ("Potassium dichromate formula", "K2Cr2O7"),
    ("Potassium fluoride formula", "KF"),
    ("Potassium hydroxide formula", "KOH"),
    ("Potassium hypochlorite formula", "KClO"),
    ("Potassium iodide formula", "KI"),
    ("Potassium dihydrogen phosphate formula", "KH2PO4"),
    ("Potassium nitrate formula", "KNO3"),
    ("Potassium nitrite formula", "KNO2"),
    ("Potassium oxide formula", "K2O"),
    ("Potassium iodate formula", "KIO3"),
    ("Potassium phosphate formula", "KH2PO4"),
    ("Potassium sulfite formula", "K2SO3"),
    ("Salicylic acid formula", "C7H6O3"),
    ("Silicon dioxide formula", "SiO2"),
    ("Silver acetate formula", "AgC2H3O2"),
    ("Silver carbonate formula", "Ag2CO3"),
    ("Silver chloride formula", "AgCl"),
    ("Silver nitrate formula", "AgNO3"),
    ("Silver oxide formula", "Ag2O"),
    ("Silver phosphate formula", "Ag3PO4"),
    ("Sodium acetate formula", "C2H3NaO2"),
    ("Sodium bicarbonate formula", "NaHCO3"),
    ("Sodium bromide formula", "NaBr"),
    ("Sodium thiosulfate formula", "Na2S2O3"),
    ("Sodium carbonate formula", "Na2CO3"),
    ("Sodium chloride formula", "NaCl"),
    ("Sodium chromate formula", "Na2CrO4"),
    ("Sodium citrate formula", "Na3C6H5O7"),
    ("Sodium cyanide formula", "NaCN"),
    ("Sodium dichromate formula", "Na2Cr2O7"),
    ("Sodium fluoride formula", "NaF"),
    ("Sodium hydroxide formula", "NaOH"),
    ("Sodium hypochlorite formula", "NaClO"),
    ("Sodium iodide formula", "NaI"),
    ("Uric acid formula", "C5H4N4O3"),
    ("Sodium nitrate formula", "NaNO3"),
    ("Sodium nitride formula", "Na3N"),
    ("Sodium nitrite formula", "NaNO2"),
    ("Sodium oxide formula", "Na2O"),
    ("Sodium peroxide formula", "Na2O2"),
    ("Sodium phosphate formula", "Na3PO4"),
    ("Sodium sulfate formula", "Na2SO4"),
    ("Sodium sulfide formula", "Na2S"),
    ("Sodium sulfite formula", "Na2SO3"),
    ("Strontium chloride formula", "SrCl2"),
    ("Strontium nitrate formula", "Sr(NO3)2"),
    ("Sucrose formula", "C12H22O11"),
    ("Sugar formula", "C12H22O11"),
    ("Sulfur dioxide formula", "SO2"),
    ("Sulfur trioxide formula", "SO3"),
    ("Sulfuric acid formula", "H2SO4"),
    ("Sulfurous acid formula", "H2SO3"),
    ("Tartaric acid formula", "C4H6O6"),
    ("Toluene formula", "C7H8"),
    ("Urea formula", "CH4N2O"),
    ("Vinegar formula", "C2H4O2"),
    ("Zinc acetate formula", "Zn(O2CCH3)2"),
    ("Zinc carbonate formula", "ZnCO3"),
    ("Zinc chloride formula", "ZnCl2"),
    ("Zinc hydroxide formula", "Zn(OH)2"),
    ("Zinc iodide formula", "ZnI2"),
    ("Zinc nitrate formula", "Zn(NO3)2"),
    ("Zinc phosphate formula", "Zn3(PO4)2"),
    ("Zinc sulfate formula", "ZnSO4"),
    ("Zinc sulfide formula", "ZnS"),
];

#[test]
fn test_parser() {
    for (i, (name, formula)) in NAMED_FORMULAS.iter().enumerate() {
        let parsed = MolecularFormula::from_str(formula);
        if let Err(e) = parsed {
            panic!(
                "Case {i}/{} - Failed to parse \"{name}\" with formula \"{formula}\": {e:?}",
                NAMED_FORMULAS.len(),
            );
        }
    }

    for formula in COMPLEX_FORMULAS {
        let parsed = MolecularFormula::from_str(formula);
        if let Err(e) = parsed {
            panic!("Failed to parse formula {formula}: {e:?}");
        }
    }
}
