//! This module contains the nested structs for the database tables.
//!
//! This file is automatically generated. Do not write anything here.

use std::rc::Rc;

#[derive(PartialEq, Debug, Clone, serde::Serialize, serde::Deserialize, Default)]
pub struct NestedSampleTaxon {
    pub inner: crate::database::flat_variants::SampleTaxon,
    pub created_by: Rc<crate::database::nested_variants::NestedUser>,
    pub sample: Rc<crate::database::nested_variants::NestedSample>,
    pub taxon: Rc<crate::database::nested_variants::NestedTaxon>,
}

unsafe impl Send for NestedSampleTaxon {}
unsafe impl Sync for NestedSampleTaxon {}
impl crate::database::Tabular for NestedSampleTaxon {
    const TABLE: crate::database::Table = crate::database::Table::SampleTaxa;
}
impl crate::database::Filtrable for NestedSampleTaxon {
    type Filter = crate::database::filter_variants::SampleTaxonFilter;
}
impl crate::database::Describable for NestedSampleTaxon {
    fn description(&self) -> Option<&str> {
        self.inner.description()
    }
}
impl crate::database::Colorable for NestedSampleTaxon {
    fn color(&self) -> Option<&str> {
        None
    }
}
#[cfg(feature = "frontend")]
impl crate::database::AllRecords for NestedSampleTaxon {
    fn all_records<C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut>(
        filter: Option<&<Self as crate::database::Filtrable>::Filter>,
        limit: Option<i64>,
        offset: Option<i64>,
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> impl std::future::Future<Output = Result<Vec<Self>, crate::api::ApiError>> {
        Self::all(filter, limit, offset, connection)
    }
}
#[cfg(feature = "frontend")]
impl NestedSampleTaxon {
    /// Convert the flat struct to the nested struct.
    ///
    /// # Arguments
    /// * `flat_variant` - The flat struct.
    /// * `connection` - The database connection.
    pub(crate) async fn from_flat(
        flat_variant: crate::database::flat_variants::SampleTaxon,
        connection: &mut gluesql::prelude::Glue<
            impl gluesql::core::store::GStore + gluesql::core::store::GStoreMut,
        >,
    ) -> Result<Self, crate::api::ApiError> {
        Ok(Self {
            created_by: Rc::from(
                crate::database::nested_variants::NestedUser::get(
                    flat_variant.created_by,
                    connection,
                )
                .await?
                .unwrap(),
            ),
            sample: Rc::from(
                crate::database::nested_variants::NestedSample::get(
                    flat_variant.sample_id,
                    connection,
                )
                .await?
                .unwrap(),
            ),
            taxon: Rc::from(
                crate::database::nested_variants::NestedTaxon::get(
                    flat_variant.taxon_id,
                    connection,
                )
                .await?
                .unwrap(),
            ),
            inner: flat_variant,
        })
    }
    /// Get the created_by attribute.
    pub fn get_created_by<E>(&self) -> &E
    where
        i32: AsRef<E>,
    {
        self.inner.get_created_by()
    }
    /// Get the created_at attribute.
    pub fn get_created_at<E>(&self) -> &E
    where
        chrono::NaiveDateTime: AsRef<E>,
    {
        self.inner.get_created_at()
    }
    /// Get the sample_id attribute.
    pub fn get_sample_id<E>(&self) -> &E
    where
        uuid::Uuid: AsRef<E>,
    {
        self.inner.get_sample_id()
    }
    /// Get the taxon_id attribute.
    pub fn get_taxon_id<E>(&self) -> &E
    where
        i32: AsRef<E>,
    {
        self.inner.get_taxon_id()
    }
    /// Get the SampleTaxon from the database by its ID.
    ///
    /// * `( sample_id, taxon_id )` - The primary key(s) of the struct to check.
    /// * `connection` - The connection to the database.
    pub async fn get<C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut>(
        (sample_id, taxon_id): (uuid::Uuid, i32),
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> Result<Option<Self>, crate::api::ApiError> {
        if let Some(flat_variant) =
            crate::database::flat_variants::SampleTaxon::get((sample_id, taxon_id), connection)
                .await?
        {
            Ok(Some(Self::from_flat(flat_variant, connection).await?))
        } else {
            Ok(None)
        }
    }
    /// Delete the SampleTaxon from the database.
    ///
    /// * `connection` - The connection to the database.
    pub async fn delete<C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut>(
        self,
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> Result<usize, crate::api::ApiError> {
        self.inner.delete(connection).await
    }
    /// Delete the SampleTaxon from the database by its ID.
    ///
    /// * `( sample_id, taxon_id )` - The primary key(s) of the struct to delete.
    /// * `connection` - The connection to the database.
    pub async fn delete_from_id<
        C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut,
    >(
        (sample_id, taxon_id): (uuid::Uuid, i32),
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> Result<usize, crate::api::ApiError> {
        crate::database::flat_variants::SampleTaxon::delete_from_id(
            (sample_id, taxon_id),
            connection,
        )
        .await
    }
    /// Get all SampleTaxon from the database.
    ///
    /// * `filter` - The filter to apply to the results.
    /// * `limit` - The maximum number of results, by default `10`.
    /// * `offset` - The offset of the results, by default `0`.
    /// * `connection` - The connection to the database.
    pub async fn all<C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut>(
        filter: Option<&crate::database::filter_variants::SampleTaxonFilter>,
        limit: Option<i64>,
        offset: Option<i64>,
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> Result<Vec<Self>, crate::api::ApiError> {
        let mut sample_taxa = Vec::new();
        for flat_variant in
            crate::database::flat_variants::SampleTaxon::all(filter, limit, offset, connection)
                .await?
                .into_iter()
        {
            sample_taxa.push(Self::from_flat(flat_variant, connection).await?);
        }
        Ok(sample_taxa)
    }
    /// Update or insert the record in the database.
    ///
    /// * `connection` - The connection to the database.
    pub async fn update_or_insert<
        C: gluesql::core::store::GStore + gluesql::core::store::GStoreMut,
    >(
        &self,
        connection: &mut gluesql::prelude::Glue<C>,
    ) -> Result<usize, crate::api::ApiError> {
        crate::database::nested_variants::NestedUser::update_or_insert(
            self.created_by.as_ref(),
            connection,
        )
        .await?;
        crate::database::nested_variants::NestedSample::update_or_insert(
            self.sample.as_ref(),
            connection,
        )
        .await?;
        crate::database::nested_variants::NestedTaxon::update_or_insert(
            self.taxon.as_ref(),
            connection,
        )
        .await?;
        crate::database::flat_variants::SampleTaxon::update_or_insert(&self.inner, connection).await
    }
}
