//! Submodule for the `pg_catalog.pg_attribute` table schema.

diesel::table! {
    /// `pg_attribute` — system catalog containing one row for each column (attribute) in a table,
    /// index, view, composite type, or foreign table.
    /// Stores metadata about column names, types, storage, nullability, defaults, identity, and inheritance.
    pg_catalog.pg_attribute (attrelid, attname, atttypid) {
        /// OID of the relation containing this column (references `pg_class.oid`).
        attrelid -> Oid,
        /// Name of the column.
        attname -> Text,
        /// OID of the column's data type (references `pg_type.oid`).
        atttypid -> Oid,
        /// Internal storage length of the column type.
        /// -1 = variable-length, -2 = C-string.
        attlen -> SmallInt,
        /// Column number:
        /// Positive = user-defined columns,
        /// 0 = table OID column,
        /// Negative = system columns.
        attnum -> SmallInt,
        /// Column offset in the tuple (for internal use by the executor).
        /// -1 if not cached.
        attcacheoff -> Integer,
        /// Type-specific modifier (atttypmod), often indicating precision/scale for numeric types.
        /// -1 if not applicable.
        atttypmod -> Integer,
        /// Number of array dimensions, if the column is an array; 0 if not.
        attndims -> SmallInt,
        /// `true` if the column's type is passed by value.
        attbyval -> Bool,
        /// Alignment requirement of the column type:
        /// 'c' = char, 's' = short, 'i' = int, 'd' = double.
        attalign -> Char,
        /// Storage strategy:
        /// 'p' = plain,
        /// 'e' = external,
        /// 'm' = main,
        /// 'x' = extended.
        attstorage -> Char,
        /// `true` if the column is marked NOT NULL.
        attnotnull -> Bool,
        /// `true` if the column has a default value.
        atthasdef -> Bool,
        /// `true` if the column has a missing value defined (for dropped/added columns).
        atthasmissing -> Bool,
        /// Identity column property:
        /// '' = not an identity column,
        /// 'a' = generated always,
        /// 'd' = generated by default.
        attidentity -> Char,
        /// Generated column property:
        /// '' = not generated,
        /// 's' = stored (generated always stored).
        attgenerated -> Char,
        /// `true` if the column has been dropped (still present for compatibility).
        attisdropped -> Bool,
        /// `true` if the column is locally defined (not inherited).
        attislocal -> Bool,
        /// Number of times this column is inherited from parent tables.
        attinhcount -> SmallInt,
        /// OID of the collation of the column, or 0 if not collatable.
        attcollation -> Oid,
        /// Target number of statistics samples for `ANALYZE`;
        /// -1 uses default setting; `NULL` if not set.
        attstattarget -> Nullable<SmallInt>,
        /// Column-level access privileges (ACL); `NULL` if none.
        attacl -> Nullable<Array<Text>>,
        /// Column-level options (e.g., for storage parameters); `NULL` if none.
        attoptions -> Nullable<Array<Text>>,
        /// Options for foreign data wrapper columns; `NULL` if none.
        attfdwoptions -> Nullable<Array<Text>>,
        /// Compression method for the column: 'p' = pglz, 'l' = lz4, or '' if no compression.
        attcompression -> Text,
    }
}

use super::pg_type::pg_type;
diesel::allow_tables_to_appear_in_same_query!(pg_attribute, pg_type);

use super::pg_class::pg_class;
diesel::allow_tables_to_appear_in_same_query!(pg_attribute, pg_class);

use super::pg_namespace::pg_namespace;
diesel::allow_tables_to_appear_in_same_query!(pg_attribute, pg_namespace);

use crate::schema::pg_catalog::pg_description::pg_description;
diesel::allow_tables_to_appear_in_same_query!(pg_attribute, pg_description);
