[package]
name = "validation_errors"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel.workspace = true
instrument_categories.workspace = true
serde.workspace = true
cas_codes.workspace = true
molecular_formulas.workspace = true
media_types.workspace = true
