[package]
name = "validation_errors"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel.workspace = true
instrument_categories.workspace = true
serde.workspace = true
cas_codes = { workspace = true, features = ["serde"] }
molecular_formulas = { workspace = true, features = ["serde"] }
media_types = { workspace = true, features = ["serde"] }

[lints]
workspace = true
