[package]
name = "backend-request-errors"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
generic-backend-request-errors.workspace = true
core-structures = { workspace = true, features = ["serde"] }
web_common_traits.workspace = true

[lints]
workspace = true
