//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Boollt, " < ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<` operator.
pub trait HasBoollt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Bool>
{
    /// The function to create the `Boollt` struct representing the `<` operator.
    fn boollt<Rhs>(self, rhs: Rhs) -> Boollt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Bool>,
    {
        Boollt::new(self, rhs.as_expression())
    }
}

impl<T> HasBoollt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Bool>
{
}
