//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(CashEq, " = ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `=` operator.
pub trait HasCashEq:
    Sized + diesel::expression::Expression<SqlType = diesel::pg::sql_types::Money>
{
    /// The function to create the `CashEq` struct representing the `=` operator.
    fn cash_eq<Rhs>(self, rhs: Rhs) -> CashEq<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::pg::sql_types::Money>,
    {
        CashEq::new(self, rhs.as_expression())
    }
}

impl<T> HasCashEq for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::pg::sql_types::Money>
{
}
