//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(CashDivFlt4, " / ", diesel::pg::sql_types::Money, backend: diesel::pg::Pg);
/// Trait for the `/` operator.
pub trait HasCashDivFlt4:
    Sized + diesel::expression::Expression<SqlType = diesel::pg::sql_types::Money>
{
    /// The function to create the `CashDivFlt4` struct representing the `/` operator.
    fn cash_div_flt4<Rhs>(self, rhs: Rhs) -> CashDivFlt4<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Float>,
    {
        CashDivFlt4::new(self, rhs.as_expression())
    }
}

impl<T> HasCashDivFlt4 for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::pg::sql_types::Money>
{
}
