//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Charne, " <> ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<>` operator.
pub trait HasCharne:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::CChar>
{
    /// The function to create the `Charne` struct representing the `<>` operator.
    fn charne<Rhs>(self, rhs: Rhs) -> Charne<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::CChar>,
    {
        Charne::new(self, rhs.as_expression())
    }
}

impl<T> HasCharne for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::CChar>
{
}
