//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DateGt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasDateGt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
    /// The function to create the `DateGt` struct representing the `>` operator.
    fn date_gt<Rhs>(self, rhs: Rhs) -> DateGt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Date>,
    {
        DateGt::new(self, rhs.as_expression())
    }
}

impl<T> HasDateGt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
}
