//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DatetimetzPl, " + ", diesel::sql_types::Timestamp, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasDatetimetzPl:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
    /// The function to create the `DatetimetzPl` struct representing the `+` operator.
    fn datetimetz_pl<Rhs>(self, rhs: Rhs) -> DatetimetzPl<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Time>,
    {
        DatetimetzPl::new(self, rhs.as_expression())
    }
}

impl<T> HasDatetimetzPl for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
}
