//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DateGtTimestamptz, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasDateGtTimestamptz:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
    /// The function to create the `DateGtTimestamptz` struct representing the `>` operator.
    fn date_gt_timestamptz<Rhs>(self, rhs: Rhs) -> DateGtTimestamptz<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        DateGtTimestamptz::new(self, rhs.as_expression())
    }
}

impl<T> HasDateGtTimestamptz for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
}
