//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(DatePli, " + ", diesel::sql_types::Date, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasDatePli:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
    /// The function to create the `DatePli` struct representing the `+` operator.
    fn date_pli<Rhs>(self, rhs: Rhs) -> DatePli<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Integer>,
    {
        DatePli::new(self, rhs.as_expression())
    }
}

impl<T> HasDatePli for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Date>
{
}
