//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Float48pl, " + ", diesel::sql_types::Double, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasFloat48pl:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Float>
{
    /// The function to create the `Float48pl` struct representing the `+` operator.
    fn float48pl<Rhs>(self, rhs: Rhs) -> Float48pl<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Double>,
    {
        Float48pl::new(self, rhs.as_expression())
    }
}

impl<T> HasFloat48pl for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Float>
{
}
