//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Float84gt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasFloat84gt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Double>
{
    /// The function to create the `Float84gt` struct representing the `>` operator.
    fn float84gt<Rhs>(self, rhs: Rhs) -> Float84gt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Float>,
    {
        Float84gt::new(self, rhs.as_expression())
    }
}

impl<T> HasFloat84gt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Double>
{
}
