//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(GeographyOverlaps, " && ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `&&` operator.
pub trait HasGeographyOverlaps:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geography>
{
    /// The function to create the `GeographyOverlaps` struct representing the `&&` operator.
    fn geography_overlaps<Rhs>(self, rhs: Rhs) -> GeographyOverlaps<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geography>,
    {
        GeographyOverlaps::new(self, rhs.as_expression())
    }
}

impl<T> HasGeographyOverlaps for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geography>
{
}
