//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Int48pl, " + ", diesel::sql_types::BigInt, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasInt48pl:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Integer>
{
    /// The function to create the `Int48pl` struct representing the `+` operator.
    fn int48pl<Rhs>(self, rhs: Rhs) -> Int48pl<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::BigInt>,
    {
        Int48pl::new(self, rhs.as_expression())
    }
}

impl<T> HasInt48pl for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Integer>
{
}
