//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(IntervalPlTimestamp, " + ", diesel::sql_types::Timestamp, backend: diesel::pg::Pg);
/// Trait for the `+` operator.
pub trait HasIntervalPlTimestamp:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
    /// The function to create the `IntervalPlTimestamp` struct representing the `+` operator.
    fn interval_pl_timestamp<Rhs>(self, rhs: Rhs) -> IntervalPlTimestamp<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        IntervalPlTimestamp::new(self, rhs.as_expression())
    }
}

impl<T> HasIntervalPlTimestamp for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Interval>
{
}
