//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(JsonArrayElement, " -> ", diesel::sql_types::Json, backend: diesel::pg::Pg);
/// Trait for the `->` operator.
pub trait HasJsonArrayElement:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Json>
{
    /// The function to create the `JsonArrayElement` struct representing the `->` operator.
    fn json_array_element<Rhs>(self, rhs: Rhs) -> JsonArrayElement<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Integer>,
    {
        JsonArrayElement::new(self, rhs.as_expression())
    }
}

impl<T> HasJsonArrayElement for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Json>
{
}
