//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(JsonbArrayElement, " -> ", diesel::sql_types::Jsonb, backend: diesel::pg::Pg);
/// Trait for the `->` operator.
pub trait HasJsonbArrayElement:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Jsonb>
{
    /// The function to create the `JsonbArrayElement` struct representing the `->` operator.
    fn jsonb_array_element<Rhs>(self, rhs: Rhs) -> JsonbArrayElement<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Integer>,
    {
        JsonbArrayElement::new(self, rhs.as_expression())
    }
}

impl<T> HasJsonbArrayElement for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Jsonb>
{
}
