//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(MacaddrGe, " >= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>=` operator.
pub trait HasMacaddrGe:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::MacAddr>
{
    /// The function to create the `MacaddrGe` struct representing the `>=` operator.
    fn macaddr_ge<Rhs>(self, rhs: Rhs) -> MacaddrGe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::MacAddr>,
    {
        MacaddrGe::new(self, rhs.as_expression())
    }
}

impl<T> HasMacaddrGe for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::MacAddr>
{
}
