//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(MulDInterval, " * ", diesel::sql_types::Interval, backend: diesel::pg::Pg);
/// Trait for the `*` operator.
pub trait HasMulDInterval:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Double>
{
    /// The function to create the `MulDInterval` struct representing the `*` operator.
    fn mul_d_interval<Rhs>(self, rhs: Rhs) -> MulDInterval<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Interval>,
    {
        MulDInterval::new(self, rhs.as_expression())
    }
}

impl<T> HasMulDInterval for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Double>
{
}
