//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(NetworkGt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasNetworkGt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Inet>
{
    /// The function to create the `NetworkGt` struct representing the `>` operator.
    fn network_gt<Rhs>(self, rhs: Rhs) -> NetworkGt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Inet>,
    {
        NetworkGt::new(self, rhs.as_expression())
    }
}

impl<T> HasNetworkGt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Inet>
{
}
