//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(NumericDiv, " / ", diesel::sql_types::Numeric, backend: diesel::pg::Pg);
/// Trait for the `/` operator.
pub trait HasNumericDiv:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Numeric>
{
    /// The function to create the `NumericDiv` struct representing the `/` operator.
    fn numeric_div<Rhs>(self, rhs: Rhs) -> NumericDiv<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Numeric>,
    {
        NumericDiv::new(self, rhs.as_expression())
    }
}

impl<T> HasNumericDiv for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Numeric>
{
}
