//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(NumericLe, " <= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<=` operator.
pub trait HasNumericLe:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Numeric>
{
    /// The function to create the `NumericLe` struct representing the `<=` operator.
    fn numeric_le<Rhs>(self, rhs: Rhs) -> NumericLe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Numeric>,
    {
        NumericLe::new(self, rhs.as_expression())
    }
}

impl<T> HasNumericLe for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Numeric>
{
}
