//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(Oidge, " >= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>=` operator.
pub trait HasOidge:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Oid>
{
    /// The function to create the `Oidge` struct representing the `>=` operator.
    fn oidge<Rhs>(self, rhs: Rhs) -> Oidge<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Oid>,
    {
        Oidge::new(self, rhs.as_expression())
    }
}

impl<T> HasOidge for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Oid>
{
}
