//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(OnSl, " <@ ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<@` operator.
pub trait HasOnSl:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `OnSl` struct representing the `<@` operator.
    fn on_sl<Rhs>(self, rhs: Rhs) -> OnSl<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        OnSl::new(self, rhs.as_expression())
    }
}

impl<T> HasOnSl for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
