//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(PointNe, " <> ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<>` operator.
pub trait HasPointNe:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `PointNe` struct representing the `<>` operator.
    fn point_ne<Rhs>(self, rhs: Rhs) -> PointNe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        PointNe::new(self, rhs.as_expression())
    }
}

impl<T> HasPointNe for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
