//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(PolyContained, " <@ ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<@` operator.
pub trait HasPolyContained:
    Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
    /// The function to create the `PolyContained` struct representing the `<@` operator.
    fn poly_contained<Rhs>(self, rhs: Rhs) -> PolyContained<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<postgis_diesel::sql_types::Geometry>,
    {
        PolyContained::new(self, rhs.as_expression())
    }
}

impl<T> HasPolyContained for T where
    T: Sized + diesel::expression::Expression<SqlType = postgis_diesel::sql_types::Geometry>
{
}
