//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(RecordImageEq, " *= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `*=` operator.
pub trait HasRecordImageEq:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Record>
{
    /// The function to create the `RecordImageEq` struct representing the `*=` operator.
    fn record_image_eq<Rhs>(self, rhs: Rhs) -> RecordImageEq<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Record>,
    {
        RecordImageEq::new(self, rhs.as_expression())
    }
}

impl<T> HasRecordImageEq for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Record>
{
}
