//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(RecordGt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasRecordGt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Record>
{
    /// The function to create the `RecordGt` struct representing the `>` operator.
    fn record_gt<Rhs>(self, rhs: Rhs) -> RecordGt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Record>,
    {
        RecordGt::new(self, rhs.as_expression())
    }
}

impl<T> HasRecordGt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Record>
{
}
