//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TextPatternLe, " ~<=~ ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `~<=~` operator.
pub trait HasTextPatternLe:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Text>
{
    /// The function to create the `TextPatternLe` struct representing the `~<=~` operator.
    fn text_pattern_le<Rhs>(self, rhs: Rhs) -> TextPatternLe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Text>,
    {
        TextPatternLe::new(self, rhs.as_expression())
    }
}

impl<T> HasTextPatternLe for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Text>
{
}
