//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimestampEqDate, " = ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `=` operator.
pub trait HasTimestampEqDate:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
    /// The function to create the `TimestampEqDate` struct representing the `=` operator.
    fn timestamp_eq_date<Rhs>(self, rhs: Rhs) -> TimestampEqDate<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Date>,
    {
        TimestampEqDate::new(self, rhs.as_expression())
    }
}

impl<T> HasTimestampEqDate for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
}
