//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimeMiInterval, " - ", diesel::sql_types::Time, backend: diesel::pg::Pg);
/// Trait for the `-` operator.
pub trait HasTimeMiInterval:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
    /// The function to create the `TimeMiInterval` struct representing the `-` operator.
    fn time_mi_interval<Rhs>(self, rhs: Rhs) -> TimeMiInterval<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Interval>,
    {
        TimeMiInterval::new(self, rhs.as_expression())
    }
}

impl<T> HasTimeMiInterval for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
}
