//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimestampGt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasTimestampGt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
    /// The function to create the `TimestampGt` struct representing the `>` operator.
    fn timestamp_gt<Rhs>(self, rhs: Rhs) -> TimestampGt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        TimestampGt::new(self, rhs.as_expression())
    }
}

impl<T> HasTimestampGt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
}
