//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimestampLt, " < ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<` operator.
pub trait HasTimestampLt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
    /// The function to create the `TimestampLt` struct representing the `<` operator.
    fn timestamp_lt<Rhs>(self, rhs: Rhs) -> TimestampLt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Timestamp>,
    {
        TimestampLt::new(self, rhs.as_expression())
    }
}

impl<T> HasTimestampLt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Timestamp>
{
}
