//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TimetzGe, " >= ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>=` operator.
pub trait HasTimetzGe:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
    /// The function to create the `TimetzGe` struct representing the `>=` operator.
    fn timetz_ge<Rhs>(self, rhs: Rhs) -> TimetzGe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Time>,
    {
        TimetzGe::new(self, rhs.as_expression())
    }
}

impl<T> HasTimetzGe for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Time>
{
}
