//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TsqMcontains, " @> ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `@>` operator.
pub trait HasTsqMcontains:
    Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsQuery>
{
    /// The function to create the `TsqMcontains` struct representing the `@>` operator.
    fn tsq_mcontains<Rhs>(self, rhs: Rhs) -> TsqMcontains<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel_full_text_search::TsQuery>,
    {
        TsqMcontains::new(self, rhs.as_expression())
    }
}

impl<T> HasTsqMcontains for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsQuery>
{
}
