//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TsvectorNe, " <> ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `<>` operator.
pub trait HasTsvectorNe:
    Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsVector>
{
    /// The function to create the `TsvectorNe` struct representing the `<>` operator.
    fn tsvector_ne<Rhs>(self, rhs: Rhs) -> TsvectorNe<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel_full_text_search::TsVector>,
    {
        TsvectorNe::new(self, rhs.as_expression())
    }
}

impl<T> HasTsvectorNe for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsVector>
{
}
