//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(TsvectorEq, " = ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `=` operator.
pub trait HasTsvectorEq:
    Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsVector>
{
    /// The function to create the `TsvectorEq` struct representing the `=` operator.
    fn tsvector_eq<Rhs>(self, rhs: Rhs) -> TsvectorEq<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel_full_text_search::TsVector>,
    {
        TsvectorEq::new(self, rhs.as_expression())
    }
}

impl<T> HasTsvectorEq for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel_full_text_search::TsVector>
{
}
