//! This file is automatically generated by the code generation suite.
//! Do not edit it manually.
//!
//! This file contains the bindings for the SQL operators in the database.

diesel::infix_operator!(UuidGt, " > ", diesel::sql_types::Bool, backend: diesel::pg::Pg);
/// Trait for the `>` operator.
pub trait HasUuidGt:
    Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Uuid>
{
    /// The function to create the `UuidGt` struct representing the `>` operator.
    fn uuid_gt<Rhs>(self, rhs: Rhs) -> UuidGt<Self, Rhs::Expression>
    where
        Rhs: diesel::expression::AsExpression<diesel::sql_types::Uuid>,
    {
        UuidGt::new(self, rhs.as_expression())
    }
}

impl<T> HasUuidGt for T where
    T: Sized + diesel::expression::Expression<SqlType = diesel::sql_types::Uuid>
{
}
