[package]
name = "font_awesome"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
csv.workspace = true

[lints]
workspace = true
