[package]
name = "directus_migration_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
webcodegen.workspace = true
quote.workspace = true
const_format.workspace = true
diesel = { workspace = true, features = ["postgres"] }

[lints]
workspace = true
