[package]
name = "core_structures_vis"
version = "0.1.0"
edition = "2024"

[dependencies]
core_structures.workspace = true
mermaid.workspace = true
diesel.workspace = true
web_common_traits.workspace = true
graph.workspace = true
sorted_vec.workspace = true
algebra.workspace = true

[lints]
workspace = true
