[package]
name = "pgrx_validation"
version = "0.0.0"
edition = "2024"

[lib]
# crate-type = ["cdylib", "lib"]
# Commented out to avoid building a shared library for the generic compilation targets,
# and unfortunately it is not possible (to my knowledge) to conditionally set the crate-type
# based on the target or features in Cargo.toml. Therefore, there is in this directory instead
# a DockerCargo.toml file that is used to build the shared library for the pgrx validation
# library in the Docker container.
crate-type = ["lib"]

[[bin]]
name = "pgrx_embed_pgrx_validation"
path = "./src/bin/pgrx_embed.rs"

[dependencies]
pgrx = { workspace = true, optional = true }
pgrx-tests = { workspace = true, optional = true }
pgrx_validation_derive.workspace = true
validation-errors.workspace = true
validator.workspace = true
rosetta-uuid.workspace = true
phf.workspace = true
rosetta-timestamp.workspace = true

[features]
default = []
pgrx = [
  "dep:pgrx",
  "pgrx_validation_derive/pgrx",
  "rosetta-uuid/pgrx",
  "rosetta-timestamp/pgrx",
]
pg13 = ["pgrx", "pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx", "pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx", "pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx", "pgrx/pg16", "pgrx-tests/pg16"]
pg17 = ["pgrx", "pgrx/pg17", "pgrx-tests/pg17"]
pg_test = ["pgrx", "dep:pgrx-tests"]
