-- UP MIGRATION
CREATE TABLE IF NOT EXISTS samples (
    id UUID PRIMARY KEY,
    created_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    sampled_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER NOT NULL REFERENCES users(id) ON
    DELETE CASCADE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    procedure_id UUID NOT NULL REFERENCES sampling_procedures(id) ON
    DELETE CASCADE,
    state INTEGER NOT NULL REFERENCES sample_states(id) ON
    DELETE CASCADE
);