#[cfg(feature = "postgres")]
impl web_common_traits::prelude::Upsertable<diesel::PgConnection>
    for crate::codegen::structs_codegen::tables::projects::Project
{
    fn upsert(
        &self,
        conn: &mut diesel::PgConnection,
    ) -> Result<Option<Self>, diesel::result::Error> {
        use diesel::{ExpressionMethods, RunQueryDsl, query_dsl::methods::FilterDsl};
        diesel::insert_into(
                crate::codegen::diesel_codegen::tables::projects::projects::table,
            )
            .values(self)
            .on_conflict(crate::codegen::diesel_codegen::tables::projects::projects::id)
            .do_update()
            .set(self)
            .filter(
                diesel::BoolExpressionMethods::and(
                    diesel::BoolExpressionMethods::and(
                        diesel::BoolExpressionMethods::and(
                            diesel::BoolExpressionMethods::and(
                                diesel::BoolExpressionMethods::and(
                                    diesel::BoolExpressionMethods::and(
                                        diesel::BoolExpressionMethods::and(
                                            diesel::BoolExpressionMethods::and(
                                                diesel::BoolExpressionMethods::and(
                                                    diesel::BoolExpressionMethods::and(
                                                        diesel::BoolExpressionMethods::and(
                                                            diesel::BoolExpressionMethods::and(
                                                                diesel::BoolExpressionMethods::and(
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::name
                                                                        .ne(
                                                                            diesel::upsert::excluded(
                                                                                crate::codegen::diesel_codegen::tables::projects::projects::name,
                                                                            ),
                                                                        ),
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::description
                                                                        .ne(
                                                                            diesel::upsert::excluded(
                                                                                crate::codegen::diesel_codegen::tables::projects::projects::description,
                                                                            ),
                                                                        ),
                                                                ),
                                                                crate::codegen::diesel_codegen::tables::projects::projects::state_id
                                                                    .ne(
                                                                        diesel::upsert::excluded(
                                                                            crate::codegen::diesel_codegen::tables::projects::projects::state_id,
                                                                        ),
                                                                    ),
                                                            ),
                                                            crate::codegen::diesel_codegen::tables::projects::projects::icon
                                                                .ne(
                                                                    diesel::upsert::excluded(
                                                                        crate::codegen::diesel_codegen::tables::projects::projects::icon,
                                                                    ),
                                                                ),
                                                        ),
                                                        crate::codegen::diesel_codegen::tables::projects::projects::color_id
                                                            .ne(
                                                                diesel::upsert::excluded(
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::color_id,
                                                                ),
                                                            ),
                                                    ),
                                                    crate::codegen::diesel_codegen::tables::projects::projects::parent_project_id
                                                        .ne(
                                                            diesel::upsert::excluded(
                                                                crate::codegen::diesel_codegen::tables::projects::projects::parent_project_id,
                                                            ),
                                                        ),
                                                ),
                                                crate::codegen::diesel_codegen::tables::projects::projects::budget
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::projects::projects::budget,
                                                        ),
                                                    ),
                                            ),
                                            crate::codegen::diesel_codegen::tables::projects::projects::expenses
                                                .ne(
                                                    diesel::upsert::excluded(
                                                        crate::codegen::diesel_codegen::tables::projects::projects::expenses,
                                                    ),
                                                ),
                                        ),
                                        crate::codegen::diesel_codegen::tables::projects::projects::created_by
                                            .ne(
                                                diesel::upsert::excluded(
                                                    crate::codegen::diesel_codegen::tables::projects::projects::created_by,
                                                ),
                                            ),
                                    ),
                                    crate::codegen::diesel_codegen::tables::projects::projects::created_at
                                        .ne(
                                            diesel::upsert::excluded(
                                                crate::codegen::diesel_codegen::tables::projects::projects::created_at,
                                            ),
                                        ),
                                ),
                                crate::codegen::diesel_codegen::tables::projects::projects::updated_by
                                    .ne(
                                        diesel::upsert::excluded(
                                            crate::codegen::diesel_codegen::tables::projects::projects::updated_by,
                                        ),
                                    ),
                            ),
                            crate::codegen::diesel_codegen::tables::projects::projects::updated_at
                                .ne(
                                    diesel::upsert::excluded(
                                        crate::codegen::diesel_codegen::tables::projects::projects::updated_at,
                                    ),
                                ),
                        ),
                        crate::codegen::diesel_codegen::tables::projects::projects::expected_end_date
                            .ne(
                                diesel::upsert::excluded(
                                    crate::codegen::diesel_codegen::tables::projects::projects::expected_end_date,
                                ),
                            ),
                    ),
                    crate::codegen::diesel_codegen::tables::projects::projects::end_date
                        .ne(
                            diesel::upsert::excluded(
                                crate::codegen::diesel_codegen::tables::projects::projects::end_date,
                            ),
                        ),
                ),
            )
            .get_results(conn)
            .map(|mut result| { result.pop() })
    }
}
#[cfg(feature = "sqlite")]
impl web_common_traits::prelude::Upsertable<diesel::SqliteConnection>
    for crate::codegen::structs_codegen::tables::projects::Project
{
    fn upsert(
        &self,
        conn: &mut diesel::SqliteConnection,
    ) -> Result<Option<Self>, diesel::result::Error> {
        use diesel::{ExpressionMethods, RunQueryDsl, query_dsl::methods::FilterDsl};
        diesel::insert_into(
                crate::codegen::diesel_codegen::tables::projects::projects::table,
            )
            .values(self)
            .on_conflict(crate::codegen::diesel_codegen::tables::projects::projects::id)
            .do_update()
            .set(self)
            .filter(
                diesel::BoolExpressionMethods::and(
                    diesel::BoolExpressionMethods::and(
                        diesel::BoolExpressionMethods::and(
                            diesel::BoolExpressionMethods::and(
                                diesel::BoolExpressionMethods::and(
                                    diesel::BoolExpressionMethods::and(
                                        diesel::BoolExpressionMethods::and(
                                            diesel::BoolExpressionMethods::and(
                                                diesel::BoolExpressionMethods::and(
                                                    diesel::BoolExpressionMethods::and(
                                                        diesel::BoolExpressionMethods::and(
                                                            diesel::BoolExpressionMethods::and(
                                                                diesel::BoolExpressionMethods::and(
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::name
                                                                        .ne(
                                                                            diesel::upsert::excluded(
                                                                                crate::codegen::diesel_codegen::tables::projects::projects::name,
                                                                            ),
                                                                        ),
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::description
                                                                        .ne(
                                                                            diesel::upsert::excluded(
                                                                                crate::codegen::diesel_codegen::tables::projects::projects::description,
                                                                            ),
                                                                        ),
                                                                ),
                                                                crate::codegen::diesel_codegen::tables::projects::projects::state_id
                                                                    .ne(
                                                                        diesel::upsert::excluded(
                                                                            crate::codegen::diesel_codegen::tables::projects::projects::state_id,
                                                                        ),
                                                                    ),
                                                            ),
                                                            crate::codegen::diesel_codegen::tables::projects::projects::icon
                                                                .ne(
                                                                    diesel::upsert::excluded(
                                                                        crate::codegen::diesel_codegen::tables::projects::projects::icon,
                                                                    ),
                                                                ),
                                                        ),
                                                        crate::codegen::diesel_codegen::tables::projects::projects::color_id
                                                            .ne(
                                                                diesel::upsert::excluded(
                                                                    crate::codegen::diesel_codegen::tables::projects::projects::color_id,
                                                                ),
                                                            ),
                                                    ),
                                                    crate::codegen::diesel_codegen::tables::projects::projects::parent_project_id
                                                        .ne(
                                                            diesel::upsert::excluded(
                                                                crate::codegen::diesel_codegen::tables::projects::projects::parent_project_id,
                                                            ),
                                                        ),
                                                ),
                                                crate::codegen::diesel_codegen::tables::projects::projects::budget
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::projects::projects::budget,
                                                        ),
                                                    ),
                                            ),
                                            crate::codegen::diesel_codegen::tables::projects::projects::expenses
                                                .ne(
                                                    diesel::upsert::excluded(
                                                        crate::codegen::diesel_codegen::tables::projects::projects::expenses,
                                                    ),
                                                ),
                                        ),
                                        crate::codegen::diesel_codegen::tables::projects::projects::created_by
                                            .ne(
                                                diesel::upsert::excluded(
                                                    crate::codegen::diesel_codegen::tables::projects::projects::created_by,
                                                ),
                                            ),
                                    ),
                                    crate::codegen::diesel_codegen::tables::projects::projects::created_at
                                        .ne(
                                            diesel::upsert::excluded(
                                                crate::codegen::diesel_codegen::tables::projects::projects::created_at,
                                            ),
                                        ),
                                ),
                                crate::codegen::diesel_codegen::tables::projects::projects::updated_by
                                    .ne(
                                        diesel::upsert::excluded(
                                            crate::codegen::diesel_codegen::tables::projects::projects::updated_by,
                                        ),
                                    ),
                            ),
                            crate::codegen::diesel_codegen::tables::projects::projects::updated_at
                                .ne(
                                    diesel::upsert::excluded(
                                        crate::codegen::diesel_codegen::tables::projects::projects::updated_at,
                                    ),
                                ),
                        ),
                        crate::codegen::diesel_codegen::tables::projects::projects::expected_end_date
                            .ne(
                                diesel::upsert::excluded(
                                    crate::codegen::diesel_codegen::tables::projects::projects::expected_end_date,
                                ),
                            ),
                    ),
                    crate::codegen::diesel_codegen::tables::projects::projects::end_date
                        .ne(
                            diesel::upsert::excluded(
                                crate::codegen::diesel_codegen::tables::projects::projects::end_date,
                            ),
                        ),
                ),
            )
            .get_results(conn)
            .map(|mut result| { result.pop() })
    }
}
