#[cfg(feature = "postgres")]
impl web_common_traits::prelude::Upsertable<diesel::PgConnection>
    for crate::codegen::structs_codegen::tables::rooms::Room
{
    fn upsert(
        &self,
        conn: &mut diesel::PgConnection,
    ) -> Result<Option<Self>, diesel::result::Error> {
        use diesel::{ExpressionMethods, RunQueryDsl, query_dsl::methods::FilterDsl};
        diesel::insert_into(crate::codegen::diesel_codegen::tables::rooms::rooms::table)
            .values(self)
            .on_conflict(crate::codegen::diesel_codegen::tables::rooms::rooms::id)
            .do_update()
            .set(self)
            .filter(
                diesel::BoolExpressionMethods::and(
                    diesel::BoolExpressionMethods::and(
                        diesel::BoolExpressionMethods::and(
                            diesel::BoolExpressionMethods::and(
                                diesel::BoolExpressionMethods::and(
                                    diesel::BoolExpressionMethods::and(
                                        diesel::BoolExpressionMethods::and(
                                            diesel::BoolExpressionMethods::and(
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::name
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::rooms::rooms::name,
                                                        ),
                                                    ),
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::description
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::rooms::rooms::description,
                                                        ),
                                                    ),
                                            ),
                                            crate::codegen::diesel_codegen::tables::rooms::rooms::qrcode
                                                .ne(
                                                    diesel::upsert::excluded(
                                                        crate::codegen::diesel_codegen::tables::rooms::rooms::qrcode,
                                                    ),
                                                ),
                                        ),
                                        crate::codegen::diesel_codegen::tables::rooms::rooms::addresses_id
                                            .ne(
                                                diesel::upsert::excluded(
                                                    crate::codegen::diesel_codegen::tables::rooms::rooms::addresses_id,
                                                ),
                                            ),
                                    ),
                                    crate::codegen::diesel_codegen::tables::rooms::rooms::geolocation
                                        .ne(
                                            diesel::upsert::excluded(
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::geolocation,
                                            ),
                                        ),
                                ),
                                crate::codegen::diesel_codegen::tables::rooms::rooms::created_by
                                    .ne(
                                        diesel::upsert::excluded(
                                            crate::codegen::diesel_codegen::tables::rooms::rooms::created_by,
                                        ),
                                    ),
                            ),
                            crate::codegen::diesel_codegen::tables::rooms::rooms::created_at
                                .ne(
                                    diesel::upsert::excluded(
                                        crate::codegen::diesel_codegen::tables::rooms::rooms::created_at,
                                    ),
                                ),
                        ),
                        crate::codegen::diesel_codegen::tables::rooms::rooms::updated_by
                            .ne(
                                diesel::upsert::excluded(
                                    crate::codegen::diesel_codegen::tables::rooms::rooms::updated_by,
                                ),
                            ),
                    ),
                    crate::codegen::diesel_codegen::tables::rooms::rooms::updated_at
                        .ne(
                            diesel::upsert::excluded(
                                crate::codegen::diesel_codegen::tables::rooms::rooms::updated_at,
                            ),
                        ),
                ),
            )
            .get_results(conn)
            .map(|mut result| { result.pop() })
    }
}
#[cfg(feature = "sqlite")]
impl web_common_traits::prelude::Upsertable<diesel::SqliteConnection>
    for crate::codegen::structs_codegen::tables::rooms::Room
{
    fn upsert(
        &self,
        conn: &mut diesel::SqliteConnection,
    ) -> Result<Option<Self>, diesel::result::Error> {
        use diesel::{ExpressionMethods, RunQueryDsl, query_dsl::methods::FilterDsl};
        diesel::insert_into(crate::codegen::diesel_codegen::tables::rooms::rooms::table)
            .values(self)
            .on_conflict(crate::codegen::diesel_codegen::tables::rooms::rooms::id)
            .do_update()
            .set(self)
            .filter(
                diesel::BoolExpressionMethods::and(
                    diesel::BoolExpressionMethods::and(
                        diesel::BoolExpressionMethods::and(
                            diesel::BoolExpressionMethods::and(
                                diesel::BoolExpressionMethods::and(
                                    diesel::BoolExpressionMethods::and(
                                        diesel::BoolExpressionMethods::and(
                                            diesel::BoolExpressionMethods::and(
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::name
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::rooms::rooms::name,
                                                        ),
                                                    ),
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::description
                                                    .ne(
                                                        diesel::upsert::excluded(
                                                            crate::codegen::diesel_codegen::tables::rooms::rooms::description,
                                                        ),
                                                    ),
                                            ),
                                            crate::codegen::diesel_codegen::tables::rooms::rooms::qrcode
                                                .ne(
                                                    diesel::upsert::excluded(
                                                        crate::codegen::diesel_codegen::tables::rooms::rooms::qrcode,
                                                    ),
                                                ),
                                        ),
                                        crate::codegen::diesel_codegen::tables::rooms::rooms::addresses_id
                                            .ne(
                                                diesel::upsert::excluded(
                                                    crate::codegen::diesel_codegen::tables::rooms::rooms::addresses_id,
                                                ),
                                            ),
                                    ),
                                    crate::codegen::diesel_codegen::tables::rooms::rooms::geolocation
                                        .ne(
                                            diesel::upsert::excluded(
                                                crate::codegen::diesel_codegen::tables::rooms::rooms::geolocation,
                                            ),
                                        ),
                                ),
                                crate::codegen::diesel_codegen::tables::rooms::rooms::created_by
                                    .ne(
                                        diesel::upsert::excluded(
                                            crate::codegen::diesel_codegen::tables::rooms::rooms::created_by,
                                        ),
                                    ),
                            ),
                            crate::codegen::diesel_codegen::tables::rooms::rooms::created_at
                                .ne(
                                    diesel::upsert::excluded(
                                        crate::codegen::diesel_codegen::tables::rooms::rooms::created_at,
                                    ),
                                ),
                        ),
                        crate::codegen::diesel_codegen::tables::rooms::rooms::updated_by
                            .ne(
                                diesel::upsert::excluded(
                                    crate::codegen::diesel_codegen::tables::rooms::rooms::updated_by,
                                ),
                            ),
                    ),
                    crate::codegen::diesel_codegen::tables::rooms::rooms::updated_at
                        .ne(
                            diesel::upsert::excluded(
                                crate::codegen::diesel_codegen::tables::rooms::rooms::updated_at,
                            ),
                        ),
                ),
            )
            .get_results(conn)
            .map(|mut result| { result.pop() })
    }
}
