CREATE TABLE IF NOT EXISTS container_models (
	id INTEGER PRIMARY KEY REFERENCES products(id),
	liters REAL NOT NULL CHECK (must_be_strictly_positive_f32(liters)),
	created_by INTEGER NOT NULL REFERENCES users(id),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by INTEGER NOT NULL REFERENCES users(id),
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);