CREATE TABLE IF NOT EXISTS organism_locations (
	id UUID PRIMARY KEY,
	organism_id UUID NOT NULL REFERENCES organisms(id),
	geolocation GEOGRAPHY(POINT, 4326) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by INTEGER NOT NULL REFERENCES users(id)
);