[package]
name = "example_extension"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_example_extension"
path = "./src/bin/pgrx_embed.rs"

[dependencies]
serde.workspace = true
diesel = { workspace = true, features = ["postgres"] }
pgrx = { workspace = true, optional = true }
diesel_pgrx = { workspace = true, features = ["postgres"] }

[features]
default = []
pgrx = ["dep:pgrx"]
pg13 = ["pgrx", "pgrx/pg13"]
pg14 = ["pgrx", "pgrx/pg14"]
pg15 = ["pgrx", "pgrx/pg15"]
pg16 = ["pgrx", "pgrx/pg16"]
pg17 = ["pgrx", "pgrx/pg17"]
sqlite = ["diesel/sqlite", "diesel_pgrx/sqlite"]

[lints]
workspace = true