services:
  example_extension:
    build:
      context: .
      dockerfile: ../../../shared_docker_files/PGRXDocker
      args:
        HOST_UID: ${USER_ID}
        HOST_GID: ${GROUP_ID}
    environment:
      - HOST_UID=${USER_ID}
      - HOST_GID=${GROUP_ID}
    container_name: example_extension_builder
    volumes:
      - ../../../:/workspace  # Mount the entire monorepo
      - ./extension:/home/appuser/extension # Output directory
    working_dir: /workspace/utils/diesel_pgrx/example_extension
    entrypoint: ["/workspace/shared_docker_files/pgrx_build.sh"]
    user: "${USER_ID}:${GROUP_ID}"
