CREATE TABLE IF NOT EXISTS instrument_models (
	id INTEGER PRIMARY KEY REFERENCES products(id),
	instrument_type_id SMALLINT NOT NULL REFERENCES instrument_types(id),
	created_by INTEGER NOT NULL REFERENCES users(id),
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by INTEGER NOT NULL REFERENCES users(id),
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);