[package]
name = "injection-sequence-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_with.workspace = true
sophia_sparql_client.workspace = true
sophia_api.workspace = true


[lints]
workspace = true

[dev-dependencies]
csv.workspace = true