pub mod tables;
pub mod types;
#[allow(unused_imports)]
pub use tables::{
    Address, AliquotingProcedure, AliquotingProcedureTemplate, Asset, AssetCompatibilityRule,
    AssetModel, AssetModelAncestor, BallMillMachine, BallMillMachineModel, BallMillProcedure,
    BallMillProcedureTemplate, BeadModel, Brand, Camera, CameraModel, CapModel, CappingProcedure,
    CappingProcedureTemplate, Centrifuge, CentrifugeModel, CentrifugeProcedure,
    CentrifugeProcedureTemplate, City, CleaningProcedure, CleaningProcedureTemplate, Color,
    CommercialBallMillMachineLot, CommercialBallMillMachineModel, CommercialBeadLot,
    CommercialBeadModel, CommercialCameraLot, CommercialCameraModel, CommercialCapLot,
    CommercialCapModel, CommercialCentrifugeLot, CommercialCentrifugeModel,
    CommercialFreezeDryerLot, CommercialFreezeDryerModel, CommercialFreezerLot,
    CommercialFreezerModel, CommercialPackagingLot, CommercialPackagingModel, CommercialPipetteLot,
    CommercialPipetteModel, CommercialPipetteTipLot, CommercialPipetteTipModel,
    CommercialPositioningDeviceLot, CommercialPositioningDeviceModel, CommercialProduct,
    CommercialProductLot, CommercialVolumeMeasuringDeviceLot, CommercialVolumeMeasuringDeviceModel,
    CommercialWeighingDeviceLot, CommercialWeighingDeviceModel, Container,
    ContainerCompatibilityRule, ContainerModel, Country, DigitalAsset, DigitalAssetModel,
    DisposalProcedure, DisposalProcedureTemplate, EmailProvider, FractioningProcedure,
    FractioningProcedureTemplate, FreezeDryer, FreezeDryerModel, FreezeDryingProcedure,
    FreezeDryingProcedureTemplate, Freezer, FreezerModel, FreezingProcedure,
    FreezingProcedureTemplate, GeolocationProcedure, GeolocationProcedureTemplate,
    HarvestingProcedure, HarvestingProcedureTemplate, InstrumentState, LoginProvider, Material,
    NextProcedureTemplate, ObservationSubject, Organism, OrganismModel, OrganismTaxon,
    Organization, PackagingModel, PackagingProcedure, PackagingProcedureTemplate,
    ParentProcedureTemplate, PermanenceCategory, PersonalProtectiveEquipmentModel, PhoneModel,
    Photograph, PhotographProcedure, PhotographProcedureTemplate, PhysicalAsset,
    PhysicalAssetModel, Pipette, PipetteModel, PipetteTipModel, PositioningDevice,
    PositioningDeviceModel, PouringProcedure, PouringProcedureTemplate, PpeReminderProcedure,
    PpeReminderProcedureTemplate, Procedure, ProcedureAsset, ProcedureTemplate,
    ProcedureTemplateAssetModel, Project, ProjectState, Rank, ReagentModel, Role, Room, Sample,
    SampleModel, SampleSource, SampleSourceModel, SampleState, Soil, SoilModel, SpatialRefSy,
    SpectraCollection, Spectrum, StorageProcedure, StorageProcedureTemplate, SupernatantProcedure,
    SupernatantProcedureTemplate, TaggingProcedure, TaggingProcedureTemplate, Taxon, Team,
    TeamMember, TeamProject, TeamState, TemporaryUser, Unit, User, UserEmail, UserOrganization,
    VolumeMeasuringDevice, VolumeMeasuringDeviceModel, VolumetricContainer,
    VolumetricContainerModel, WeighingDevice, WeighingDeviceModel, WeighingProcedure,
    WeighingProcedureTemplate,
};
