//! Submodule defining DB constraints for procedure and procedure template
//! tables.

mod procedure_alignment;
mod procedure_primary_key;
mod procedure_template_primary_key;
mod procedure_to_procedure_template_foreign_key;
mod unused_foreign_procedure_template;
pub use procedure_alignment::ProcedureAlignmentConstraint;
pub use procedure_primary_key::ProcedurePrimaryKeyConstraint;
pub use procedure_template_primary_key::ProcedureTemplatePrimaryKeyConstraint;
pub use procedure_to_procedure_template_foreign_key::ProcedureToProcedureTemplateForeignKeyConstraint;
pub use unused_foreign_procedure_template::UnusedForeignProcedureTemplateConstraint;
