[package]
name = "cas_code"
version = "0.1.0"
edition = "2024"

# [lib]
# crate-type = ["cdylib", "lib"]

[[bin]]
name = "pgrx_embed_cas_code"
path = "./src/bin/pgrx_embed.rs"

[dependencies]
serde.workspace = true
pgrx = { workspace = true, optional = true }
diesel.workspace = true
strum_macros.workspace = true
strum.workspace = true
diesel_pgrx.workspace = true

[features]
default = []
sqlite = ["diesel/sqlite", "diesel_pgrx/sqlite"]
postgres = ["diesel/postgres", "diesel_pgrx/postgres"]

pgrx = ["dep:pgrx"]
pg13 = ["pgrx", "pgrx/pg13"]
pg14 = ["pgrx", "pgrx/pg14"]
pg15 = ["pgrx", "pgrx/pg15"]
pg16 = ["pgrx", "pgrx/pg16"]
pg17 = ["pgrx", "pgrx/pg17"]
