services:
  cas_code:
    build:
      context: .
      dockerfile: ../../../shared_docker_files/PGRXDocker
      args:
        HOST_UID: ${USER_ID}
        HOST_GID: ${GROUP_ID}
    environment:
      - HOST_UID=${USER_ID}
      - HOST_GID=${GROUP_ID}
    container_name: cas_code_builder
    volumes:
      - ../../..:/workspace  # Mount the entire monorepo
      - ./extension:/home/appuser/extension # Output directory
    working_dir: /workspace/web/web_common/cas_code
    entrypoint: ["/workspace/web/web_common/cas_code/build.sh"]
    user: "${USER_ID}:${GROUP_ID}"
