-- SQL defining a document to be stored on the server
-- The document is a file that is uploaded by a user or generated by the server
-- The document is stored in the file system and the path to the file is stored in the database
-- The document is associated with a user who created it and the user is stored in the database
-- The document has a name and a description that are stored in the database, with the name 
-- being the file name provided by the user and the description being a user-provided description.
-- The path itself does not contain the file name itself, as it may be dangerous to let the user
-- specify the path of the file. 
CREATE TABLE documents (
    id BIGINT PRIMARY KEY REFERENCES editables(id) ON DELETE CASCADE REFERENCES describables(id) ON DELETE CASCADE,
    path VARCHAR(255) NOT NULL,
    format_id BIGINT NOT NULL REFERENCES document_formats(id) ON DELETE CASCADE,
    bytes INTEGER NOT NULL
);