name: Clippy

on:
  push:
    paths:
      - 'utils/diesel_pgrx/example_extension/**'
  pull_request:
    paths:
      - 'utils/diesel_pgrx/example_extension/**'

jobs:
  clippy:
    uses: ./.github/workflows/cargo-clippy-template.yml
    with:
      path: 'utils/diesel_pgrx/example_extension'
