name: Clippy Check Reusable

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  clippy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings