name: Clippy

on:
  push:
    paths:
      - 'utils/diesel_pgrx/**'
  pull_request:
    paths:
      - 'utils/diesel_pgrx/**'

jobs:
  clippy:
    uses: ./.github/workflows/cargo-clippy-template.yml
    with:
      path: 'utils/diesel_pgrx'
