name: Cargo Test Reusable

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Run cargo test
        run: cargo test --all-targets
