name: TOML Format

on:
    push:
      paths:
        - '**/Cargo.toml'
    pull_request:
      paths:
        - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  format:
    name: TOML Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Taplo CLI
        uses: taiki-e/install-action@fa23953489c080190314742a9b907f8e97c6767c # v2
        with:
          tool: taplo-cli

      - name: Check TOML formatting
        run: taplo fmt --check