name: TOML Format

on:
    push:
      paths:
        - '**/Cargo.toml'
    pull_request:
      paths:
        - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: TOML Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Taplo CLI
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Check TOML formatting
        run: taplo fmt --check