name: Cargo Format

on:
  push:
    paths:
      - '**/*.rs'
  pull_request:
    paths:
      - '**/*.rs'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check