name: TOML Format

on:
    push:
      paths:
        - '**/Cargo.toml'
    pull_request:
      paths:
        - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  format:
    name: TOML Check Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install Taplo CLI
        uses: taiki-e/install-action@7b8d4719ee4aaa279bdf55df38dacb9ebfe12a6c # v2
        with:
          tool: taplo-cli

      - name: Check TOML formatting
        run: taplo fmt --check