name: Validate JSON

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Validate changed JSON files
        run: |
          echo "Validating modified JSON files..."
          FILES=$(git diff --name-only --diff-filter=AMR ${{ github.event.before }} ${{ github.sha }} | grep '\.json$' || true)
          
          if [ -z "$FILES" ]; then
            echo "No JSON files to validate."
            exit 0
          fi

          ERRORS=0
          for file in $FILES; do
            echo "Checking $file"
            if ! python -m json.tool "$file" > /dev/null 2>&1; then
              echo "❌ Invalid JSON: $file"
              ERRORS=1
            else
              echo "✅ Valid JSON: $file"
            fi
          done

          if [ $ERRORS -ne 0 ]; then
            echo "One or more JSON files are invalid."
            exit 1
          fi
