name: PGRX Build

on:
  push:
    paths:
      - 'utils/diesel_pgrx/example_extension/**'
  pull_request:
    paths:
      - 'utils/diesel_pgrx/example_extension/**'

jobs:
  call-build:
    uses: ./.github/workflows/pgrx-build-template.yml
    with:
      path: utils/diesel_pgrx/example_extension
