name: Build Service Reusable

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose
        run: |
          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          USER_ID=$USER_ID GROUP_ID=$GROUP_ID docker compose up --build --abort-on-container-exit
