name: Sirius


on:
  push:
    paths:
      - "bindings/sirius_bindings/**"
  pull_request:
    paths:
      - "bindings/sirius_bindings/**"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  sirius:
    runs-on: ubuntu-latest
    environment: Sirius
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Retrieve Sirius install script
        run: |
          wget https://raw.githubusercontent.com/enpkg/enpkg_full/emikg-adapt/src/install_sirius.sh
          chmod +x install_sirius.sh
      - name: Install Sirius
        run: |
          bash ./install_sirius.sh
          chmod +x ./sirius/bin
      - name: Set up Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        env:
          SIRIUS_USERNAME: ${{secrets.SIRIUS_USERNAME}}
          SIRIUS_PASSWORD: ${{secrets.SIRIUS_PASSWORD}}
        run: | 
          export SIRIUS_PATH=${{vars.SIRIUS_PATH}}
          cargo test --package sirius_bindings

