[package]
name = "csqlv-macro"
version = "0.1.2"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
csqlv.workspace = true
macro-utils.workspace = true
quote.workspace = true
sql_minifier.workspace = true
syn.workspace = true

[lints]
workspace = true

[features]
iso_codes = ["csqlv/iso_codes"]