name: ${DOCKER_PROJECT_NAME}
services:
  postgres:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: ${POSTGRES_DOCKER_NAME}
    build:
      dockerfile: PostgresDockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../:/app
    ports:
      - "${PGPORT}:5432"
    networks:
      - develop_backend
    # restart: on-failure

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - ./pgadmin/servers.json:/pgadmin4/servers.json
  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   networks:
  #     - develop_backend
  #   depends_on:
  #     - postgres
  #   restart: on-failure

  redis:
    image: redis:latest
    command: --port ${REDIS_PORT}
    networks:
      - develop_backend
    restart: on-failure

  actix-server:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ACTIX_PORT: ${ACTIX_PORT}
        HOST_UID: ${USER_ID}
        HOST_GID: ${GROUP_ID}
    environment:
      HOST_UID: ${USER_ID}
      HOST_GID: ${GROUP_ID}
      POSTGRES_DB: ${POSTGRES_DB}
      DOCKER_DATABASE_URL: ${DOCKER_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_REDIRECT_URI: ${GITHUB_REDIRECT_URI}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
      SIRIUS_USERNAME: ${SIRIUS_USERNAME}
      SIRIUS_PASSWORD: ${SIRIUS_PASSWORD}
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
      ACCESS_TOKEN_MINUTES: ${ACCESS_TOKEN_MINUTES}
      REFRESH_TOKEN_MINUTES: ${REFRESH_TOKEN_MINUTES}
      ACTIX_PORT: ${ACTIX_PORT}
      ACTIX_WORKER_THREADS: ${ACTIX_WORKER_THREADS}
      DOMAIN: ${DOMAIN}
    volumes:
      - ../:/home/appuser/app
    depends_on:
      - postgres
      - redis
    networks:
      - develop_backend
    restart: on-failure

  yew-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./frontend
      args:
        TRUNK_PORT: ${TRUNK_PORT}
        ACTIX_PORT: ${ACTIX_PORT}
        HOST_UID: ${USER_ID}
        HOST_GID: ${GROUP_ID}
    environment:
      HOST_UID: ${USER_ID}
      HOST_GID: ${GROUP_ID}
      TRUNK_PORT: ${TRUNK_PORT}
      DOMAIN: ${DOMAIN}
      ACTIX_PORT: ${ACTIX_PORT}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
    volumes:
      - ../:/home/appuser/app
    depends_on:
      - actix-server
    networks:
      - develop_frontend
      - develop_backend
    restart: on-failure

  nginx:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ./nginx
      args:
        HOST_UID: ${USER_ID}
        HOST_GID: ${GROUP_ID}
    volumes:
      - ./nginx:/app
    environment:
      HOST_UID: ${USER_ID}
      HOST_GID: ${GROUP_ID}
      ACTIX_PORT: ${ACTIX_PORT}
      TRUNK_PORT: ${TRUNK_PORT}
      NGINX_HTTPS_PORT: ${NGINX_HTTPS_PORT}
      DOMAIN: ${DOMAIN}
      NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES}
    ports:
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    depends_on:
      - actix-server
      - yew-frontend
    networks:
      - develop_frontend
      - develop_backend
    restart: on-failure

networks:
  develop_frontend:
    driver: bridge
  develop_backend:
    driver: bridge
